name: Multi-Trigger Example

run-name: "${{ github.actor }}'s Example2 Workflow Run"

on:
  push:
    branches: [main]           
    types: [opened, synchronize]  
  workflow_dispatch:       
  schedule:
    - cron: '*/2 * * * *'      

jobs:
  show-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Print trigger
        run: "echo 'Triggered by: ${{ github.event_name }}'"
